ALTER TABLE users
MODIFY email VARCHAR(255) NOT NULL,
MODIFY password VARCHAR(255) NOT NULL,
MODIFY firstName VARCHAR(100) NOT NULL,
MODIFY lastName VARCHAR(100) NOT NULL,
MODIFY role VARCHAR(20) NOT NULL;
